# Generated by Django 3.2.5 on 2021-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transData',
            field=models.CharField(max_length=1000),
        ),
    ]
