# Generated by Django 3.2.5 on 2021-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_transactiondetails_transdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerminalID', models.CharField(max_length=30)),
                ('MerchantID', models.CharField(max_length=30)),
                ('Data', models.TextField()),
            ],
        ),
    ]
