# Generated by Django 3.2.5 on 2021-07-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='TranDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
