# Generated by Django 3.2.5 on 2021-07-29 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_test_trandate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='tranCardNo',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='tranDate',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='tranFromAccount',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='tranTime',
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='TranDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 0, 25, 11, 834944)),
        ),
    ]
