# Generated by Django 3.2.5 on 2021-07-29 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0007_auto_20210730_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Column', models.CharField(max_length=100)),
                ('Position', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='TranDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 0, 39, 42, 253960)),
        ),
    ]
