# Generated by Django 3.2.5 on 2021-07-29 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0008_auto_20210730_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='TranDate',
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='tranDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 1, 19, 27, 943458)),
        ),
    ]
